#
# LSD.TOS, March 2017 (DO NOT REMOVE THIS LINE)
#
# makefile for the common_vhdl_code directory
#

FILES  = audio_controller.vhd
FILES += blop_sound_rom.vhd
FILES += clock_generator.vhd
FILES += debouncer.vhd
FILES += font_16x16_bold.vhd
FILES += font_8x8_bold.vhd
FILES += ir_nec_decoder.vhd
FILES += lcd_controller.vhd
FILES += ps2_controller.vhd
FILES += pseudo_random_generator.vhd
FILES += pulse_generator.vhd
FILES += rs232_controller.vhd
FILES += seven_segment_decoder.vhd
FILES += sin_function.vhd
FILES += sram_controller.vhd
FILES += vga_config.vhd
FILES += vga.vhd

clean:

files:
	@for f in makefile $(FILES); do readlink -f $$f; done
